#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=GMT%2B8            # 数据库名称
    username: root
    password: root


  dbcp2:
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 200                                  # 等待连接获取

#配置项目路径
server:
  servlet:
    context-path: /seckill

logging:
  level:
    com.xdarker.dao: trace   #控制台打印sql语句

mybatis:
  mapper-locations: classpath:mappers/*.xml