#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=GMT%2B8            # 数据库名称
    username: root
    password: root

  dbcp2:
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 200                                  # 等待连接获取

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  redis:
    password:                       # Redis服务器连接密码（默认为空）
    timeout: 0ms
    commandTimeout: 5000

    jedis:
      pool:
        max-active: 8               # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 0                # 连接池中的最大空闲连接
        max-wait: -1ms              # 连接池最大阻塞等待时间（使用负值表示没有限制）

    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
  #port: 6379                       # Redis服务器连接端口
  #host: 127.0.0.1                  # Redis服务器地址

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: XDarker
    password: XDarker
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    virtual-host: /XDarker


#配置项目路径
#server:
#  servlet:
#    context-path: /seckill

logging:
  level:
    com.xdarker.dao: trace   #控制台打印sql语句

mybatis:
  mapper-locations: classpath:mappers/*.xml

